-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS hmis.anc_temp_notes
(
    anc_temp_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    staff_id integer NOT NULL,
    temperature numeric(4, 1),
    pulse_rate integer,
    respiratory_rate integer,
    blood_pressure character varying(20) COLLATE pg_catalog."default",
    weight numeric(5, 2),
    height numeric(5, 2),
    bmi numeric(4, 1),
    spo2 integer,
    lmp_date date,
    edd_date date,
    gestation_weeks integer,
    fundal_height numeric(4, 1),
    fetal_heart_rate integer,
    fetal_presentation character varying(50) COLLATE pg_catalog."default",
    fetal_movement character varying(50) COLLATE pg_catalog."default",
    fetal_lie character varying(50) COLLATE pg_catalog."default",
    gravity integer,
    parity integer,
    chief_complaint text COLLATE pg_catalog."default",
    triage_notes text COLLATE pg_catalog."default",
    billing_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'paid'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    next_visit_date date,
    hemoglobin_level numeric(4, 1),
    urine_protein character varying(20) COLLATE pg_catalog."default",
    preventive_ifas boolean DEFAULT false,
    bleeding boolean DEFAULT false,
    blurred_vision boolean DEFAULT false,
    severe_edema boolean DEFAULT false,
    fever boolean DEFAULT false,
    CONSTRAINT anc_temp_notes_pkey PRIMARY KEY (anc_temp_id)
);

CREATE TABLE IF NOT EXISTS hmis.billing_master
(
    billing_id serial NOT NULL,
    visit_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    patient_id integer NOT NULL,
    department character varying(50) COLLATE pg_catalog."default" NOT NULL,
    service_code integer NOT NULL,
    service_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL,
    total_amount numeric(12, 2) GENERATED ALWAYS AS (((quantity)::numeric * unit_price)) STORED,
    billing_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    payment_method character varying(20) COLLATE pg_catalog."default" NOT NULL,
    billed_by integer NOT NULL,
    billed_at timestamp with time zone NOT NULL DEFAULT now(),
    payment_reference character varying(100) COLLATE pg_catalog."default",
    total_price numeric(12, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT billing_master_pkey PRIMARY KEY (billing_id)
);

CREATE TABLE IF NOT EXISTS hmis.bills
(
    bill_id serial NOT NULL,
    visit_id integer NOT NULL,
    total_amount numeric(10, 2) DEFAULT 0.00,
    payment_status bills_payment_status_enum DEFAULT 'pending'::bills_payment_status_enum,
    status bills_status_enum DEFAULT 'pending'::bills_status_enum,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bills_pkey PRIMARY KEY (bill_id)
);

CREATE TABLE IF NOT EXISTS hmis.clinical_notes
(
    note_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    staff_id integer NOT NULL,
    chief_complaint text COLLATE pg_catalog."default",
    temperature numeric(4, 1),
    weight numeric(5, 2),
    height numeric(5, 2),
    bmi numeric(5, 2),
    pulse_rate integer,
    respiratory_rate integer,
    spo2 integer,
    triage_notes text COLLATE pg_catalog."default",
    history_of_present_illness text COLLATE pg_catalog."default",
    past_medical_history text COLLATE pg_catalog."default",
    past_surgical_history text COLLATE pg_catalog."default",
    drug_history text COLLATE pg_catalog."default",
    allergies text COLLATE pg_catalog."default",
    family_history text COLLATE pg_catalog."default",
    social_history text COLLATE pg_catalog."default",
    examination text COLLATE pg_catalog."default",
    provisional_diagnosis text COLLATE pg_catalog."default",
    plan text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    finalized_at timestamp with time zone,
    referral character varying(255) COLLATE pg_catalog."default",
    referral_notes text COLLATE pg_catalog."default",
    last_edited_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT clinical_notes_pkey PRIMARY KEY (note_id)
);

CREATE TABLE IF NOT EXISTS hmis.diagnoses
(
    diagnosis_id serial NOT NULL,
    icd_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    diagnosis_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT diagnoses_pkey PRIMARY KEY (diagnosis_id),
    CONSTRAINT diagnoses_icd_code_key UNIQUE (icd_code)
);

CREATE TABLE IF NOT EXISTS hmis.drugs
(
    drug_id serial NOT NULL,
    drug_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    generic_name character varying(150) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    formulation character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    strength character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    unit character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    cost_price numeric(10, 2) NOT NULL,
    selling_price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    expiry_date date,
    batch_number character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    status drug_status_enum DEFAULT 'active'::drug_status_enum,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT drugs_pkey PRIMARY KEY (drug_id)
);

CREATE TABLE IF NOT EXISTS hmis.imaging_cart
(
    cart_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    investigation_id integer NOT NULL,
    imaging_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    imaging_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cost numeric(10, 2) NOT NULL,
    status imaging_cart_status_enum NOT NULL DEFAULT 'waiting'::imaging_cart_status_enum,
    requested_by integer NOT NULL,
    performed_by integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT imaging_cart_pkey PRIMARY KEY (cart_id),
    CONSTRAINT unique_visit_test UNIQUE (visit_id, investigation_id)
);

CREATE TABLE IF NOT EXISTS hmis.imaging_investigations
(
    investigation_id serial NOT NULL,
    imaging_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    imaging_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cost numeric(10, 2) NOT NULL,
    status imaging_status_enum NOT NULL DEFAULT 'active'::imaging_status_enum,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT imaging_investigations_pkey PRIMARY KEY (investigation_id)
);

CREATE TABLE IF NOT EXISTS hmis.inventory_items
(
    item_id serial NOT NULL,
    item_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    item_category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    item_code character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    department character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    location character varying(150) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    quantity integer NOT NULL DEFAULT 1,
    purchase_date date,
    purchase_cost numeric(12, 2) DEFAULT NULL::numeric,
    current_value numeric(12, 2) DEFAULT NULL::numeric,
    item_condition item_condition_enum DEFAULT 'good'::item_condition_enum,
    status inventory_status_enum DEFAULT 'active'::inventory_status_enum,
    supplier character varying(150) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    warranty_expiry date,
    notes text COLLATE pg_catalog."default",
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS hmis.lab_cart
(
    cart_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    requested_by integer NOT NULL,
    lab_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    test_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    cost numeric(10, 2) NOT NULL DEFAULT 0.00,
    collected_by integer,
    collected_at timestamp without time zone,
    CONSTRAINT lab_cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS hmis.lab_results
(
    result_id serial NOT NULL,
    visit_id integer NOT NULL,
    test_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    parameter_id integer NOT NULL,
    value numeric(10, 2) NOT NULL,
    units character varying(20) COLLATE pg_catalog."default" NOT NULL,
    parameter_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    result_value numeric(12, 4) DEFAULT NULL::numeric,
    result_text character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    flag lab_flag_enum DEFAULT 'normal'::lab_flag_enum,
    requested_by integer NOT NULL,
    performed_by integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lab_results_pkey PRIMARY KEY (result_id)
);

CREATE TABLE IF NOT EXISTS hmis.lab_test
(
    test_id serial NOT NULL,
    test_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    test_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    loinc_code character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    specimen character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    cost numeric(12, 2) DEFAULT NULL::numeric,
    status lab_test_status_enum DEFAULT 'active'::lab_test_status_enum,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lab_test_pkey PRIMARY KEY (test_id),
    CONSTRAINT lab_test_test_code_test_code1_key UNIQUE (test_code)
        INCLUDE(test_code)
);

CREATE TABLE IF NOT EXISTS hmis.maternity_temp_notes
(
    temp_note_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    triage_id integer NOT NULL,
    temperature numeric(4, 2) DEFAULT NULL::numeric,
    pulse_rate integer,
    respiratory_rate integer,
    weight numeric(5, 2) DEFAULT NULL::numeric,
    height numeric(5, 2) DEFAULT NULL::numeric,
    bmi numeric(4, 1) DEFAULT NULL::numeric,
    spo2 integer,
    chief_complaint text COLLATE pg_catalog."default",
    triage_notes text COLLATE pg_catalog."default",
    cervical_dilation integer DEFAULT 0,
    contractions integer DEFAULT 0,
    fetal_heart_rate integer,
    moulding moulding_enum DEFAULT '0'::moulding_enum,
    descent_of_head character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    bp_systolic integer,
    bp_diastolic integer,
    lie_presentation character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status maternity_note_status_enum DEFAULT 'pending'::maternity_note_status_enum,
    CONSTRAINT maternity_temp_notes_pkey PRIMARY KEY (temp_note_id)
);

CREATE TABLE IF NOT EXISTS hmis.otc_queue
(
    otc_id serial NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default" DEFAULT 'Walk-in Customer'::character varying,
    total_amount numeric(12, 2) DEFAULT NULL::numeric,
    status otc_queue_status_enum DEFAULT 'pending'::otc_queue_status_enum,
    added_by_staff_id integer,
    payment_reference character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT otc_queue_pkey PRIMARY KEY (otc_id)
);

CREATE TABLE IF NOT EXISTS hmis.otc_queue_items
(
    item_id serial NOT NULL,
    otc_id integer,
    drug_id integer,
    drug_name character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    quantity integer,
    unit_price numeric(12, 2) DEFAULT NULL::numeric,
    subtotal numeric(12, 2) DEFAULT NULL::numeric,
    CONSTRAINT otc_queue_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS hmis.parameter
(
    parameter_id serial NOT NULL,
    test_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    parameter_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    min_value numeric(10, 2) DEFAULT NULL::numeric,
    max_value numeric(10, 2) DEFAULT NULL::numeric,
    critical_low numeric(10, 2) DEFAULT NULL::numeric,
    critical_high numeric(10, 2) DEFAULT NULL::numeric,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT parameter_pkey PRIMARY KEY (parameter_id),
    CONSTRAINT unique_test_parameter UNIQUE (test_code, parameter_name)
);

CREATE TABLE IF NOT EXISTS hmis.partograph_readings
(
    id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    fetal_heart_rate smallint,
    liquor parto_liquor_enum,
    moulding parto_moulding_enum NOT NULL DEFAULT '0'::parto_moulding_enum,
    fetal_descent parto_fetal_descent_enum,
    cervical_dilation smallint,
    contractions smallint,
    contraction_duration parto_contraction_duration_enum,
    membranes parto_membranes_enum,
    bp_systolic smallint,
    bp_diastolic smallint,
    pulse smallint,
    temperature numeric(4, 1) DEFAULT NULL::numeric,
    spo2 smallint,
    urine_output smallint,
    urine_protein parto_urine_protein_enum,
    urine_acetone parto_urine_acetone_enum,
    oxytocin_units character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    drugs_iv_fluids character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    triage_notes text COLLATE pg_catalog."default",
    recorded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partograph_readings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hmis.patients
(
    patient_id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(30) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    date_of_birth date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT patients_pkey PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS hmis.pharma_cart
(
    cart_id serial NOT NULL,
    visit_id integer NOT NULL,
    drug_id integer NOT NULL,
    drug_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price numeric(12, 2) NOT NULL,
    quantity integer NOT NULL,
    dose character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    frequency character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    duration character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    added_by_staff_id integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    payment_reference character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pharma_cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS hmis.pharmacy_inventory
(
    pharm_item_id serial NOT NULL,
    drug_id integer,
    drug_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    formulation character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    strength character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    shelf_number character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    current_qty integer DEFAULT 0,
    min_alert_qty integer DEFAULT 10,
    selling_price numeric(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT pharmacy_inventory_pkey PRIMARY KEY (pharm_item_id)
);

CREATE TABLE IF NOT EXISTS hmis.pharmacy_stock_requests
(
    request_id serial NOT NULL,
    drug_id integer NOT NULL,
    requested_qty integer NOT NULL,
    requester_id integer NOT NULL,
    status stock_request_status_enum DEFAULT 'pending'::stock_request_status_enum,
    request_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_by integer,
    processed_date timestamp without time zone,
    CONSTRAINT pharmacy_stock_requests_pkey PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS hmis.prescriptions
(
    prescription_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    drug_id integer NOT NULL,
    drug_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dose character varying(50) COLLATE pg_catalog."default" NOT NULL,
    frequency character varying(50) COLLATE pg_catalog."default" NOT NULL,
    duration character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    prescriber_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dispenser_name character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    dispensed_at timestamp without time zone,
    status prescription_status_enum DEFAULT 'PENDING'::prescription_status_enum,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT prescriptions_pkey PRIMARY KEY (prescription_id)
);

CREATE TABLE IF NOT EXISTS hmis.radiology_reports
(
    report_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    investigation_id integer NOT NULL,
    findings text COLLATE pg_catalog."default" NOT NULL,
    impression text COLLATE pg_catalog."default" NOT NULL,
    recommendations text COLLATE pg_catalog."default",
    image_path character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    performed_by integer NOT NULL,
    verified_by integer,
    report_status radiology_report_status_enum DEFAULT 'draft'::radiology_report_status_enum,
    performed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT radiology_reports_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS hmis.services
(
    service_id serial NOT NULL,
    service_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    categories character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    department character varying(50) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    status service_status_enum DEFAULT 'active'::service_status_enum,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT services_pkey PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS hmis.staff
(
    staff_id serial NOT NULL,
    full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    role character varying(80) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT staff_pkey PRIMARY KEY (staff_id)
);

CREATE TABLE IF NOT EXISTS hmis.staff_messages
(
    message_id serial NOT NULL,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    message_text text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS hmis.temp_clinical_notes
(
    temp_note_id serial NOT NULL,
    visit_id integer NOT NULL DEFAULT 0,
    patient_id integer NOT NULL,
    staff_id integer NOT NULL,
    chief_complaint text COLLATE pg_catalog."default" NOT NULL,
    temperature numeric(4, 1) DEFAULT NULL::numeric,
    weight numeric(5, 2) DEFAULT NULL::numeric,
    height numeric(5, 2) DEFAULT NULL::numeric,
    bmi numeric(5, 2) DEFAULT NULL::numeric,
    pulse_rate integer,
    respiratory_rate integer,
    spo2 integer,
    triage_notes text COLLATE pg_catalog."default",
    status clinical_note_status_enum DEFAULT 'draft'::clinical_note_status_enum,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_edited_at timestamp without time zone,
    history_of_present_illness text COLLATE pg_catalog."default",
    past_medical_history text COLLATE pg_catalog."default",
    past_surgical_history text COLLATE pg_catalog."default",
    drug_history text COLLATE pg_catalog."default",
    allergies text COLLATE pg_catalog."default",
    family_history text COLLATE pg_catalog."default",
    social_history text COLLATE pg_catalog."default",
    examination text COLLATE pg_catalog."default",
    provisional_diagnosis text COLLATE pg_catalog."default",
    plan text COLLATE pg_catalog."default",
    referral character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    referral_notes text COLLATE pg_catalog."default",
    CONSTRAINT temp_clinical_notes_pkey PRIMARY KEY (temp_note_id)
);

CREATE TABLE IF NOT EXISTS hmis.triage
(
    triage_id serial NOT NULL,
    visit_id integer NOT NULL,
    patient_id integer NOT NULL,
    temperature numeric(4, 1) DEFAULT NULL::numeric,
    pulse_rate character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    respiratory_rate integer,
    blood_pressure character varying(15) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    spo2 integer,
    weight numeric(5, 2) DEFAULT NULL::numeric,
    height numeric(5, 2) DEFAULT NULL::numeric,
    bmi numeric(5, 2) DEFAULT NULL::numeric,
    chief_complaint text COLLATE pg_catalog."default",
    triage_notes text COLLATE pg_catalog."default",
    triage_level triage_level_enum NOT NULL DEFAULT 'Routine'::triage_level_enum,
    billing_status triage_billing_status_enum DEFAULT 'pending'::triage_billing_status_enum,
    triaged_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    visit_type character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    CONSTRAINT triage_pkey PRIMARY KEY (triage_id)
);

CREATE TABLE IF NOT EXISTS hmis.visits
(
    visit_id serial NOT NULL,
    patient_id integer NOT NULL,
    staff_id integer NOT NULL,
    visit_date timestamp with time zone NOT NULL DEFAULT now(),
    department character varying(80) COLLATE pg_catalog."default" NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::character varying,
    CONSTRAINT visits_pkey PRIMARY KEY (visit_id)
);

ALTER TABLE IF EXISTS hmis.anc_temp_notes
    ADD CONSTRAINT anc_temp_notes_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.anc_temp_notes
    ADD CONSTRAINT anc_temp_notes_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.anc_temp_notes
    ADD CONSTRAINT anc_temp_notes_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS hmis.billing_master
    ADD CONSTRAINT billing_master_billed_by_fkey FOREIGN KEY (billed_by)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.billing_master
    ADD CONSTRAINT billing_master_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.clinical_notes
    ADD CONSTRAINT clinical_notes_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.clinical_notes
    ADD CONSTRAINT clinical_notes_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.clinical_notes
    ADD CONSTRAINT clinical_notes_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS hmis.imaging_cart
    ADD CONSTRAINT imaging_cart_investigation_id_fkey FOREIGN KEY (investigation_id)
    REFERENCES hmis.imaging_investigations (investigation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_img_cart_investigation
    ON hmis.imaging_cart(investigation_id);


ALTER TABLE IF EXISTS hmis.imaging_cart
    ADD CONSTRAINT imaging_cart_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.imaging_cart
    ADD CONSTRAINT imaging_cart_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.lab_cart
    ADD CONSTRAINT lab_cart_lab_code_fkey FOREIGN KEY (lab_code)
    REFERENCES hmis.lab_test (test_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_lab_cart_code
    ON hmis.lab_cart(lab_code);


ALTER TABLE IF EXISTS hmis.lab_cart
    ADD CONSTRAINT lab_cart_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_lab_cart_visit
    ON hmis.lab_cart(visit_id);


ALTER TABLE IF EXISTS hmis.lab_results
    ADD CONSTRAINT lab_results_test_code_fkey FOREIGN KEY (test_code)
    REFERENCES hmis.lab_test (test_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.lab_results
    ADD CONSTRAINT lab_results_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.maternity_temp_notes
    ADD CONSTRAINT maternity_temp_notes_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_maternity_notes_patient
    ON hmis.maternity_temp_notes(patient_id);


ALTER TABLE IF EXISTS hmis.maternity_temp_notes
    ADD CONSTRAINT maternity_temp_notes_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_maternity_notes_visit
    ON hmis.maternity_temp_notes(visit_id);


ALTER TABLE IF EXISTS hmis.parameter
    ADD CONSTRAINT parameter_test_code_fkey FOREIGN KEY (test_code)
    REFERENCES hmis.lab_test (test_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.partograph_readings
    ADD CONSTRAINT partograph_readings_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_parto_patient
    ON hmis.partograph_readings(patient_id);


ALTER TABLE IF EXISTS hmis.partograph_readings
    ADD CONSTRAINT partograph_readings_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_parto_visit
    ON hmis.partograph_readings(visit_id);


ALTER TABLE IF EXISTS hmis.pharma_cart
    ADD CONSTRAINT pharma_cart_drug_id_fkey FOREIGN KEY (drug_id)
    REFERENCES hmis.drugs (drug_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_pharma_cart_drug
    ON hmis.pharma_cart(drug_id);


ALTER TABLE IF EXISTS hmis.pharma_cart
    ADD CONSTRAINT pharma_cart_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_pharma_cart_visit
    ON hmis.pharma_cart(visit_id);


ALTER TABLE IF EXISTS hmis.pharmacy_inventory
    ADD CONSTRAINT pharmacy_inventory_drug_id_fkey FOREIGN KEY (drug_id)
    REFERENCES hmis.drugs (drug_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_pharm_inv_drug_id
    ON hmis.pharmacy_inventory(drug_id);


ALTER TABLE IF EXISTS hmis.pharmacy_stock_requests
    ADD CONSTRAINT pharmacy_stock_requests_drug_id_fkey FOREIGN KEY (drug_id)
    REFERENCES hmis.drugs (drug_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_pharm_req_drug
    ON hmis.pharmacy_stock_requests(drug_id);


ALTER TABLE IF EXISTS hmis.pharmacy_stock_requests
    ADD CONSTRAINT pharmacy_stock_requests_requester_id_fkey FOREIGN KEY (requester_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.prescriptions
    ADD CONSTRAINT prescriptions_drug_id_fkey FOREIGN KEY (drug_id)
    REFERENCES hmis.drugs (drug_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fk_prescription_drug
    ON hmis.prescriptions(drug_id);


ALTER TABLE IF EXISTS hmis.prescriptions
    ADD CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fk_prescription_patient
    ON hmis.prescriptions(patient_id);


ALTER TABLE IF EXISTS hmis.prescriptions
    ADD CONSTRAINT prescriptions_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fk_prescription_visit
    ON hmis.prescriptions(visit_id);


ALTER TABLE IF EXISTS hmis.radiology_reports
    ADD CONSTRAINT radiology_reports_investigation_id_fkey FOREIGN KEY (investigation_id)
    REFERENCES hmis.imaging_investigations (investigation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS hmis.radiology_reports
    ADD CONSTRAINT radiology_reports_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_rad_rep_patient
    ON hmis.radiology_reports(patient_id);


ALTER TABLE IF EXISTS hmis.radiology_reports
    ADD CONSTRAINT radiology_reports_performed_by_fkey FOREIGN KEY (performed_by)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_rad_rep_performed_by
    ON hmis.radiology_reports(performed_by);


ALTER TABLE IF EXISTS hmis.radiology_reports
    ADD CONSTRAINT radiology_reports_verified_by_fkey FOREIGN KEY (verified_by)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_rad_rep_verified_by
    ON hmis.radiology_reports(verified_by);


ALTER TABLE IF EXISTS hmis.staff_messages
    ADD CONSTRAINT staff_messages_receiver_id_fkey FOREIGN KEY (receiver_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_staff_msg_receiver
    ON hmis.staff_messages(receiver_id);


ALTER TABLE IF EXISTS hmis.staff_messages
    ADD CONSTRAINT staff_messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_staff_msg_sender
    ON hmis.staff_messages(sender_id);


ALTER TABLE IF EXISTS hmis.temp_clinical_notes
    ADD CONSTRAINT temp_clinical_notes_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_notes_patient
    ON hmis.temp_clinical_notes(patient_id);


ALTER TABLE IF EXISTS hmis.temp_clinical_notes
    ADD CONSTRAINT temp_clinical_notes_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_notes_visit
    ON hmis.temp_clinical_notes(visit_id);


ALTER TABLE IF EXISTS hmis.triage
    ADD CONSTRAINT triage_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fk_triage_patient
    ON hmis.triage(patient_id);


ALTER TABLE IF EXISTS hmis.triage
    ADD CONSTRAINT triage_visit_id_fkey FOREIGN KEY (visit_id)
    REFERENCES hmis.visits (visit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fk_triage_visit
    ON hmis.triage(visit_id);


ALTER TABLE IF EXISTS hmis.visits
    ADD CONSTRAINT visits_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES hmis.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS hmis.visits
    ADD CONSTRAINT visits_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES hmis.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
